# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mobile_store.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1281, 751))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 90, 921, 141))
        self.label.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")

        self.label_img = QtWidgets.QLabel(self.frame)
        self.label_img.setGeometry(QtCore.QRect(300, 300, 300, 250))
        self.pixmap = QtGui.QPixmap("image_1.png")
        self.label_img.setPixmap(self.pixmap)

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1151, 751))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(80, 50, 471, 81))
        self.label_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(740, 70, 321, 51))
        self.label_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(550, 30, 20, 661))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(90, 160, 271, 41))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(90, 200, 371, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(90, 300, 271, 41))
        self.label_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 340, 371, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(670, 160, 271, 41))
        self.label_10.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(670, 200, 371, 61))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(670, 300, 271, 41))
        self.label_11.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(670, 340, 371, 61))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(100, 590, 371, 71))
        self.pushButton.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 590, 371, 71))
        self.pushButton_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1151, 751))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(400, 20, 681, 111))
        self.label_12.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(270, 200, 831, 91))
        self.label_13.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setEnabled(True)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1161, 741))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(220, 110, 671, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 31))
        self.menubar.setObjectName("menubar")
        self.menuSignIn = QtWidgets.QMenu(self.menubar)
        self.menuSignIn.setObjectName("menuSignIn")
        self.menuCreate = QtWidgets.QMenu(self.menubar)
        self.menuCreate.setObjectName("menuCreate")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuUpdate = QtWidgets.QMenu(self.menubar)
        self.menuUpdate.setObjectName("menuUpdate")
        self.menuDelete = QtWidgets.QMenu(self.menubar)
        self.menuDelete.setObjectName("menuDelete")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionSales = QtWidgets.QAction(MainWindow)
        self.actionSales.setEnabled(False)
        self.actionSales.setObjectName("actionSales")
        self.actionEmp = QtWidgets.QAction(MainWindow)
        self.actionEmp.setEnabled(False)
        self.actionEmp.setObjectName("actionEmp")
        self.actionSales_2 = QtWidgets.QAction(MainWindow)
        self.actionSales_2.setEnabled(False)
        self.actionSales_2.setObjectName("actionSales_2")
        self.actionEmp_2 = QtWidgets.QAction(MainWindow)
        self.actionEmp_2.setEnabled(False)
        self.actionEmp_2.setObjectName("actionEmp_2")
        self.actionSales_3 = QtWidgets.QAction(MainWindow)
        self.actionSales_3.setEnabled(False)
        self.actionSales_3.setObjectName("actionSales_3")
        self.actionEmp_3 = QtWidgets.QAction(MainWindow)
        self.actionEmp_3.setEnabled(False)
        self.actionEmp_3.setObjectName("actionEmp_3")
        self.actionSales_4 = QtWidgets.QAction(MainWindow)
        self.actionSales_4.setEnabled(False)
        self.actionSales_4.setObjectName("actionSales_4")
        self.actionEmp_4 = QtWidgets.QAction(MainWindow)
        self.actionEmp_4.setEnabled(False)
        self.actionEmp_4.setObjectName("actionEmp_4")
        self.actionRegsitration = QtWidgets.QAction(MainWindow)
        self.actionRegsitration.setObjectName("actionRegsitration")
        self.menuSignIn.addSeparator()
        self.menuSignIn.addAction(self.actionLogin)
        self.menuSignIn.addAction(self.actionRegsitration)
        self.menuCreate.addAction(self.actionSales)
        self.menuCreate.addAction(self.actionEmp)
        self.menuView.addAction(self.actionSales_2)
        self.menuView.addAction(self.actionEmp_2)
        self.menuUpdate.addAction(self.actionSales_3)
        self.menuUpdate.addAction(self.actionEmp_3)
        self.menuDelete.addAction(self.actionSales_4)
        self.menuDelete.addAction(self.actionEmp_4)
        self.menubar.addAction(self.menuSignIn.menuAction())
        self.menubar.addAction(self.menuCreate.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuUpdate.menuAction())
        self.menubar.addAction(self.menuDelete.menuAction())


        self.frame_2.hide()
        self.frame_3.hide()
        self.frame_4.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to Mobile Store Management"))
        self.label_2.setText(_translate("MainWindow", "Register Now"))
        self.label_3.setText(_translate("MainWindow", "Login Now"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.label_10.setText(_translate("MainWindow", "Username"))
        self.label_11.setText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))
        self.label_12.setText(_translate("MainWindow", "Login Successfully"))
        self.label_13.setText(_translate("MainWindow", "Choose operation from above menu"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.menuSignIn.setTitle(_translate("MainWindow", "SignIn"))
        self.menuCreate.setTitle(_translate("MainWindow", "Create"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuUpdate.setTitle(_translate("MainWindow", "Update"))
        self.menuDelete.setTitle(_translate("MainWindow", "Delete"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionSales.setText(_translate("MainWindow", "Sales"))
        self.actionEmp.setText(_translate("MainWindow", "Emp"))
        self.actionSales_2.setText(_translate("MainWindow", "Sales"))
        self.actionEmp_2.setText(_translate("MainWindow", "Emp"))
        self.actionSales_3.setText(_translate("MainWindow", "Sales"))
        self.actionEmp_3.setText(_translate("MainWindow", "Emp"))
        self.actionSales_4.setText(_translate("MainWindow", "Sales"))
        self.actionEmp_4.setText(_translate("MainWindow", "Emp"))
        self.actionRegsitration.setText(_translate("MainWindow", "Regsitration"))

        self.actionLogin.triggered.connect(self.login)
        self.actionRegsitration.triggered.connect(self.register)

    def login(self):
        self.frame_2.show()

    def register(self):
        self.frame_2.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

